// All toddler activities (100 total activities)
const activities = [
    // Motor Skills Activities (24 activities)
    {
        id: 1,
        title: "Cotton Ball Transfer",
        ageRange: "2-3",
        description: "Transfer cotton balls between containers using tweezers or tongs to develop fine motor skills and hand-eye coordination.",
        materials: ["Cotton balls", "Containers", "Tongs/Tweezers"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "motor",
        skillFocus: "Fine Motor",
        messiness: "Low"
    },
    {
        id: 2,
        title: "Playdough Exploration",
        ageRange: "2-3",
        description: "Explore playdough with hands, tools, and cookie cutters to strengthen hand muscles and develop creativity.",
        materials: ["Playdough", "Cookie cutters", "Plastic tools"],
        setupTime: "2 min",
        activityLength: "15+ min",
        category: "motor",
        skillFocus: "Fine Motor",
        messiness: "Medium"
    },
    {
        id: 3,
        title: "Paper Tearing and Collage",
        ageRange: "2-3",
        description: "Tear paper into small pieces and glue them onto paper to create a collage while developing finger strength and coordination.",
        materials: ["Construction paper", "Glue stick", "Base paper"],
        setupTime: "2 min",
        activityLength: "15+ min",
        category: "motor",
        skillFocus: "Fine Motor",
        messiness: "Medium"
    },
    {
        id: 4,
        title: "Finger Painting",
        ageRange: "2-3",
        description: "Paint with fingers on paper to explore texture, colors, and develop sensory awareness while strengthening finger muscles.",
        materials: ["Non-toxic water-based finger paint", "Paper", "Smock/old shirt"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "motor",
        skillFocus: "Fine Motor",
        messiness: "High"
    },
    {
        id: 5,
        title: "Sticker/Tape Peeling and Sticking",
        ageRange: "2-3",
        description: "Peel stickers or washi tape and stick them on paper to practice fine pincer grasp and finger dexterity.",
        materials: ["Stickers", "Washi or masking tape", "Paper"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "motor",
        skillFocus: "Fine Motor",
        messiness: "Low"
    },
    {
        id: 6,
        title: "Button Board",
        ageRange: "2-3",
        description: "Push large buttons through a slit in a container lid to develop hand strength and coordination.",
        materials: ["Reused plastic container", "Large buttons", "Scissors (for adult use)"],
        setupTime: "10+ min",
        activityLength: "10 min",
        category: "motor",
        skillFocus: "Fine Motor",
        messiness: "Low"
    },
    {
        id: 7,
        title: "Ribbon Pull Box",
        ageRange: "2-3",
        description: "Pull ribbons of different textures through holes in a box to develop grip strength and hand-eye coordination.",
        materials: ["Cardboard box", "Ribbons", "Scissors (for adult use)"],
        setupTime: "10+ min",
        activityLength: "5 min",
        category: "motor",
        skillFocus: "Fine Motor",
        messiness: "Low"
    },
    {
        id: 8,
        title: "String Beads",
        ageRange: "2-3",
        description: "String large beads onto pipe cleaners or shoelaces to develop fine motor skills and hand-eye coordination.",
        materials: ["Large beads", "Pipe cleaners or shoelaces"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "motor",
        skillFocus: "Fine Motor",
        messiness: "Low"
    },
    {
        id: 9,
        title: "Clothespin Drop",
        ageRange: "2-3",
        description: "Pick up and drop clothespins into a container to strengthen pincer grip and finger muscles.",
        materials: ["Clothespins", "Container"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "motor",
        skillFocus: "Fine Motor",
        messiness: "Low"
    },
    {
        id: 10,
        title: "Water Transfer with Sponges",
        ageRange: "2-3",
        description: "Squeeze water from sponges between containers to build hand strength and practice liquid transfer.",
        materials: ["Sponges", "Water", "Two containers"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "motor",
        skillFocus: "Fine Motor",
        messiness: "Medium"
    },
    {
        id: 11,
        title: "Indoor Obstacle Course",
        ageRange: "2-3",
        description: "Navigate through simple obstacles like cushions, tunnels, and stepping stones to develop gross motor skills and coordination.",
        materials: ["Pillows", "Cushions", "Chairs", "Blankets"],
        setupTime: "10+ min",
        activityLength: "15+ min",
        category: "motor",
        skillFocus: "Gross Motor",
        messiness: "Low"
    },
    {
        id: 12,
        title: "Ball Rolling and Catching",
        ageRange: "2-3",
        description: "Roll and catch a large ball back and forth to develop coordination, balance, and visual tracking.",
        materials: ["Large soft ball"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "motor",
        skillFocus: "Gross Motor",
        messiness: "Low"
    },
    {
        id: 13,
        title: "Dance Freeze",
        ageRange: "2-3",
        description: "Dance to music and freeze when the music stops to practice balance, coordination, and following directions.",
        materials: ["Music player"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "motor",
        skillFocus: "Gross Motor",
        messiness: "Low"
    },
    {
        id: 14,
        title: "Ribbon Dancing",
        ageRange: "2-3",
        description: "Wave ribbons to music to develop arm strength, coordination, and rhythm awareness.",
        materials: ["Ribbons or scarves", "Music"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "motor",
        skillFocus: "Gross Motor",
        messiness: "Low"
    },
    {
        id: 15,
        title: "Balloon Tapping",
        ageRange: "2-3",
        description: "Keep a balloon in the air by tapping it with hands to develop eye-hand coordination and motor planning.",
        materials: ["Balloon"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "motor",
        skillFocus: "Gross Motor",
        messiness: "Low"
    },
    {
        id: 16,
        title: "Push and Pull Toys",
        ageRange: "2-3",
        description: "Push and pull toys in cardboard boxes around the room to build strength, balance, and coordination.",
        materials: ["Push/pull toys", "Empty box with string attached"],
        setupTime: "2 min",
        activityLength: "15+ min",
        category: "motor",
        skillFocus: "Gross Motor",
        messiness: "Low"
    },
    {
        id: 17,
        title: "Stepping Stones",
        ageRange: "2-3",
        description: "Step from one paper 'stone' to another to develop balance and leg strength.",
        materials: ["Paper plates or construction paper taped to floor"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "motor",
        skillFocus: "Gross Motor",
        messiness: "Low"
    },
    {
        id: 18,
        title: "Box Walking",
        ageRange: "2-3",
        description: "Walk on flattened cardboard boxes cut to a foot wide and taped to the floor to practice balance and spatial awareness.",
        materials: ["Flattened cardboard boxes"],
        setupTime: "10 min",
        activityLength: "10 min",
        category: "motor",
        skillFocus: "Gross Motor",
        messiness: "Low"
    },
    {
        id: 19,
        title: "Bubble Wrap Stomp",
        ageRange: "2-3",
        description: "Stomp on bubble wrap to develop leg strength, coordination, and sensory awareness.",
        materials: ["Bubble wrap"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "motor",
        skillFocus: "Gross Motor",
        messiness: "Low"
    },
    {
        id: 20,
        title: "Pillow Mountain Climbing",
        ageRange: "2-3",
        description: "Climb over a pile of pillows and cushions to develop climbing skills, strength, and balance.",
        materials: ["Pillows", "Cushions"],
        setupTime: "5 min",
        activityLength: "15+ min",
        category: "motor",
        skillFocus: "Gross Motor",
        messiness: "Low"
    },
    {
        id: 21,
        title: "Cotton Ball Races",
        ageRange: "2-3",
        description: "Blow cotton balls across a table with straws to develop breath control and oral motor skills.",
        materials: ["Cotton balls", "Straws", "Table or flat surface"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "motor",
        skillFocus: "Oral Motor",
        messiness: "Low"
    },
    {
        id: 22,
        title: "Coin Slot Drop",
        ageRange: "2-3",
        description: "Drop coins or poker chips into a slot cut in a plastic container lid to practice fine motor control and precision.",
        materials: ["Container with lid", "Plastic coins or poker chips", "Scissors (for adult use)"],
        setupTime: "5 min",
        activityLength: "5 min",
        category: "motor",
        skillFocus: "Fine Motor",
        messiness: "Low"
    },
    {
        id: 23,
        title: "Sidewalk Chalk Drawing",
        ageRange: "2-3",
        description: "Draw with large chalk on sidewalks or driveways to develop hand strength and artistic expression.",
        materials: ["Sidewalk chalk", "Outdoor surface"],
        setupTime: "2 min",
        activityLength: "15+ min",
        category: "motor",
        skillFocus: "Fine Motor",
        messiness: "Medium"
    },
    {
        id: 24,
        title: "Painting with Water",
        ageRange: "2-3",
        description: "Paint outdoor surfaces with water and a brush to practice brush control without the mess of real paint.",
        materials: ["Bucket of water", "Paintbrushes", "Outdoor surface"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "motor",
        skillFocus: "Fine Motor",
        messiness: "Low"
    },
    
    // Language & Communication Activities (24 activities)
    {
        id: 25,
        title: "Story Box Theatre",
        ageRange: "2-3",
        description: "Create simple story scenes in a box using toys and objects, then practice storytelling and vocabulary as you play with the characters.",
        materials: ["Shoebox", "Small toys", "Paper", "Crayons"],
        setupTime: "10+ min",
        activityLength: "15+ min",
        category: "language",
        skillFocus: "Vocabulary",
        messiness: "Low"
    },
    {
        id: 26,
        title: "Picture Book Conversation",
        ageRange: "2-3",
        description: "Look at picture books together and talk about what's happening in the images to build vocabulary and conversation skills.",
        materials: ["Picture books"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "language",
        skillFocus: "Conversation",
        messiness: "Low"
    },
    {
        id: 27,
        title: "Simon Says",
        ageRange: "2-3",
        description: "Play a simple version of Simon Says to practice following directions and learning action words.",
        materials: ["None needed"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "language",
        skillFocus: "Following Directions",
        messiness: "Low"
    },
    {
        id: 28,
        title: "Puppet Show",
        ageRange: "2-3",
        description: "Use simple sock or paper puppets to act out stories and encourage verbal expression and dialogue.",
        materials: ["Sock or paper bag puppets", "Puppet theater (optional)"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "language",
        skillFocus: "Verbal Expression",
        messiness: "Low"
    },
    {
        id: 29,
        title: "Song Basket",
        ageRange: "2-3",
        description: "Fill a basket with objects that represent different songs, and let your toddler choose which song to sing by selecting an object.",
        materials: ["Basket", "Small objects representing songs"],
        setupTime: "10+ min",
        activityLength: "10 min",
        category: "language",
        skillFocus: "Vocabulary",
        messiness: "Low"
    },
    {
        id: 30,
        title: "Action Songs",
        ageRange: "2-3",
        description: "Sing songs with actions (like 'Head, Shoulders, Knees, and Toes') to connect words with body parts and movements.",
        materials: ["None needed", "Music (optional)"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "language",
        skillFocus: "Vocabulary",
        messiness: "Low"
    },
    {
        id: 31,
        title: "Everyday Narration",
        ageRange: "2-3",
        description: "Narrate everyday activities as you do them together to build vocabulary and sentence structure awareness.",
        materials: ["None needed"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "language",
        skillFocus: "Vocabulary",
        messiness: "Low"
    },
    {
        id: 32,
        title: "Mystery Box",
        ageRange: "2-3",
        description: "Have your toddler reach into a box, feel an object, and try to describe or guess what it is before taking it out.",
        materials: ["Box with lid", "Familiar objects"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "language",
        skillFocus: "Descriptive Language",
        messiness: "Low"
    },
    {
        id: 33,
        title: "Picture Sorting and Naming",
        ageRange: "2-3",
        description: "Sort picture cards into categories while naming each item to practice categorization and vocabulary.",
        materials: ["Picture cards or magazine cutouts"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "language",
        skillFocus: "Vocabulary",
        messiness: "Low"
    },
    {
        id: 34,
        title: "Phone Calls",
        ageRange: "2-3",
        description: "Use toy phones or disconnected real phones to practice conversation skills and turn-taking in dialogue.",
        materials: ["Toy phones or old phones"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "language",
        skillFocus: "Conversation",
        messiness: "Low"
    },
    {
        id: 35,
        title: "Picture Walk",
        ageRange: "2-3",
        description: "Take a 'picture walk' through a book before reading it, discussing what might happen based on the illustrations.",
        materials: ["Picture books"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "language",
        skillFocus: "Prediction",
        messiness: "Low"
    },
    {
        id: 36,
        title: "Animal Sounds",
        ageRange: "2-3",
        description: "Match animal toys or pictures with their corresponding sounds to build vocabulary and phonological awareness.",
        materials: ["Animal toys or pictures"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "language",
        skillFocus: "Sound Production",
        messiness: "Low"
    },
    {
        id: 37,
        title: "Silly Sentences",
        ageRange: "2-3",
        description: "Create silly sentences together, substituting unexpected words to develop humor and language play.",
        materials: ["Paper and pencil for adult to write on (optional)"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "language",
        skillFocus: "Sentence Structure",
        messiness: "Low"
    },
    {
        id: 38,
        title: "I Spy Colors",
        ageRange: "2-3",
        description: "Play 'I Spy' focusing on colors to build color vocabulary and observation skills.",
        materials: ["Colorful environment"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "language",
        skillFocus: "Vocabulary",
        messiness: "Low"
    },
    {
        id: 39,
        title: "Story Sequencing Cards",
        ageRange: "2-3",
        description: "Arrange simple picture cards in sequence and tell the story that they show to develop narrative skills.",
        materials: ["Sequencing cards or simple pictures"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "language",
        skillFocus: "Sequencing",
        messiness: "Low"
    },
    {
        id: 40,
        title: "Rhyming Basket",
        ageRange: "2-3",
        description: "Collect objects that rhyme and play matching games to develop phonological awareness.",
        materials: ["Objects with rhyming names", "Basket"],
        setupTime: "10+ min",
        activityLength: "10 min",
        category: "language",
        skillFocus: "Phonological Awareness",
        messiness: "Low"
    },
    {
        id: 41,
        title: "Mirror Talk",
        ageRange: "2-3",
        description: "Talk in front of a mirror together to observe mouth movements and facial expressions during speech.",
        materials: ["Mirror"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "language",
        skillFocus: "Articulation",
        messiness: "Low"
    },
    {
        id: 42,
        title: "Nursery Rhyme Time",
        ageRange: "2-3",
        description: "Recite nursery rhymes with actions to develop rhythm, memory, and language patterns.",
        materials: ["Nursery rhyme book (optional)"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "language",
        skillFocus: "Phonological Awareness",
        messiness: "Low"
    },
    {
        id: 43,
        title: "Texture Words",
        ageRange: "2-3",
        description: "Explore and describe different textures to develop sensory vocabulary (rough, smooth, soft, etc.).",
        materials: ["Texture samples or household items with different textures"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "language",
        skillFocus: "Descriptive Language",
        messiness: "Low"
    },
    {
        id: 44,
        title: "Photo Album Stories",
        ageRange: "2-3",
        description: "Look at family photos together and talk about the people, places, and events to practice memory and narrative skills.",
        materials: ["Family photos or photo album"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "language",
        skillFocus: "Narrative Skills",
        messiness: "Low"
    },
    {
        id: 45,
        title: "Question of the Day",
        ageRange: "2-3",
        description: "Ask one simple question each day (like 'What's your favorite food?') to practice answering questions.",
        materials: ["List of simple questions"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "language",
        skillFocus: "Question Answering",
        messiness: "Low"
    },
    {
        id: 46,
        title: "Echo Games",
        ageRange: "2-3",
        description: "Say words, phrases, or make sounds for your toddler to repeat and practice pronunciation.",
        materials: ["None needed"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "language",
        skillFocus: "Pronunciation",
        messiness: "Low"
    },
    {
        id: 47,
        title: "Shopping List Game",
        ageRange: "2-3",
        description: "Pretend to go shopping and verbally create a shopping list together to practice memory and vocabulary.",
        materials: ["Toy shopping cart or bag (optional)", "Toy food items (optional)"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "language",
        skillFocus: "Memory",
        messiness: "Low"
    },
    {
        id: 48,
        title: "Body Part Labeling",
        ageRange: "2-3",
        description: "Name and point to body parts on yourself, your toddler, and on dolls or stuffed animals to build body vocabulary.",
        materials: ["Dolls or stuffed animals"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "language",
        skillFocus: "Vocabulary",
        messiness: "Low"
    },
    
    // Cognitive Development Activities (22 activities)
    {
        id: 49,
        title: "Color Sorting Cups",
        ageRange: "2-3",
        description: "Sort small objects by color into matching colored cups to practice color recognition, categorization, and fine motor skills.",
        materials: ["Colored cups", "Small objects", "Tray"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "cognitive",
        skillFocus: "Color Recognition",
        messiness: "Low"
    },
    {
        id: 50,
        title: "Shape Matching",
        ageRange: "2-3",
        description: "Match simple shapes to their outlines to develop visual discrimination and shape recognition.",
        materials: ["Shape cutouts", "Shape outline cards"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "cognitive",
        skillFocus: "Shape Recognition",
        messiness: "Low"
    },
    {
        id: 51,
        title: "Size Seriation",
        ageRange: "2-3",
        description: "Arrange objects from smallest to largest to develop understanding of size relationships.",
        materials: ["Sets of graduated objects (nesting cups, different sized blocks)"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "cognitive",
        skillFocus: "Size Comparison",
        messiness: "Low"
    },
    {
        id: 52,
        title: "Simple Puzzles",
        ageRange: "2-3",
        description: "Complete wooden or foam puzzles with few pieces to develop spatial reasoning and problem-solving.",
        materials: ["Toddler puzzles (2-6 pieces)"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "cognitive",
        skillFocus: "Problem Solving",
        messiness: "Low"
    },
    {
        id: 53,
        title: "Object Permanence Box",
        ageRange: "2-3",
        description: "Drop a ball into a box with a maze inside to understand that objects continue to exist even when out of sight.",
        materials: ["Ball drop box or homemade version"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "cognitive",
        skillFocus: "Object Permanence",
        messiness: "Low"
    },
    {
        id: 54,
        title: "Memory Matching",
        ageRange: "2-3",
        description: "Play a simple matching game with a few cards face down to develop memory and concentration.",
        materials: ["Picture cards (pairs)"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "cognitive",
        skillFocus: "Memory",
        messiness: "Low"
    },
    {
        id: 55,
        title: "Counting Objects",
        ageRange: "2-3",
        description: "Count small collections of objects together to develop number sense and one-to-one correspondence.",
        materials: ["Small objects (blocks, buttons, etc.)"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "cognitive",
        skillFocus: "Counting",
        messiness: "Low"
    },
    {
        id: 56,
        title: "Sink or Float",
        ageRange: "2-3",
        description: "Test whether different objects sink or float in water to develop prediction and observation skills.",
        materials: ["Tub of water", "Various objects", "Towel"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "cognitive",
        skillFocus: "Prediction",
        messiness: "Medium"
    },
    {
        id: 57,
        title: "Picture Matching",
        ageRange: "2-3",
        description: "Match identical pictures or objects to their pictures to develop visual discrimination.",
        materials: ["Matching cards or objects with picture cards"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "cognitive",
        skillFocus: "Visual Discrimination",
        messiness: "Low"
    },
    {
        id: 58,
        title: "Simple Pattern Blocks",
        ageRange: "2-3",
        description: "Create simple designs with pattern blocks to develop spatial awareness and early pattern recognition.",
        materials: ["Pattern blocks", "Pattern cards (optional)"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "cognitive",
        skillFocus: "Spatial Awareness",
        messiness: "Low"
    },
    {
        id: 59,
        title: "Nesting and Stacking",
        ageRange: "2-3",
        description: "Nest and stack containers of different sizes to develop size discrimination and spatial relationships.",
        materials: ["Nesting cups or containers"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "cognitive",
        skillFocus: "Size Relationships",
        messiness: "Low"
    },
    {
        id: 60,
        title: "Treasure Basket",
        ageRange: "2-3",
        description: "Explore a collection of different household objects to stimulate curiosity and investigation.",
        materials: ["Basket", "Variety of household objects with different properties"],
        setupTime: "5 min",
        activityLength: "15+ min",
        category: "cognitive",
        skillFocus: "Exploration",
        messiness: "Low"
    },
    {
        id: 61,
        title: "What's Missing Game",
        ageRange: "2-3",
        description: "Show your toddler a few objects, then remove one while they close their eyes and ask them to identify what's missing.",
        materials: ["Small collection of familiar objects"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "cognitive",
        skillFocus: "Memory",
        messiness: "Low"
    },
    {
        id: 62,
        title: "Animal Categories",
        ageRange: "2-3",
        description: "Sort animal toys or pictures into basic categories (farm, zoo, pets) to develop classification skills.",
        materials: ["Animal toys or pictures"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "cognitive",
        skillFocus: "Categorization",
        messiness: "Low"
    },
    {
        id: 63,
        title: "Simple Cause and Effect Toys",
        ageRange: "2-3",
        description: "Explore toys where an action produces a predictable effect to develop understanding of cause and effect.",
        materials: ["Jack-in-the-box", "Pop-up toys", "Push buttons"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "cognitive",
        skillFocus: "Cause and Effect",
        messiness: "Low"
    },
    {
        id: 64,
        title: "Two-Piece Puzzles",
        ageRange: "2-3",
        description: "Match two-piece puzzles where each piece completes a familiar object to develop part-whole relationships.",
        materials: ["Simple two-piece puzzles or homemade picture halves"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "cognitive",
        skillFocus: "Part-Whole Relationships",
        messiness: "Low"
    },
    {
        id: 65,
        title: "Magnet Exploration",
        ageRange: "2-3",
        description: "Test which household objects are attracted to magnets to develop prediction and classification skills.",
        materials: ["Large child-safe magnets", "Various metal and non-metal objects"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "cognitive",
        skillFocus: "Classification",
        messiness: "Low"
    },
    {
        id: 66,
        title: "Sound Matching",
        ageRange: "2-3",
        description: "Match identical sounds using containers filled with different materials (rice, beans, etc.).",
        materials: ["Containers with lids", "Different filling materials"],
        setupTime: "10+ min",
        activityLength: "10 min",
        category: "cognitive",
        skillFocus: "Auditory Discrimination",
        messiness: "Low"
    },
    {
        id: 67,
        title: "Shadow Play",
        ageRange: "2-3",
        description: "Create and observe shadows with a flashlight to understand light and shadow relationships.",
        materials: ["Flashlight", "Various objects"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "cognitive",
        skillFocus: "Cause and Effect",
        messiness: "Low"
    },
    {
        id: 68,
        title: "Nature Collecting",
        ageRange: "2-3",
        description: "Collect and examine natural objects (leaves, sticks, rocks) to develop observation and classification skills.",
        materials: ["Collection basket", "Natural items"],
        setupTime: "2 min",
        activityLength: "15+ min",
        category: "cognitive",
        skillFocus: "Observation",
        messiness: "Medium"
    },
    {
        id: 69,
        title: "Texture Matching",
        ageRange: "2-3",
        description: "Match pairs of objects with the same texture to develop tactile discrimination.",
        materials: ["Objects with various textures (two of each)"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "cognitive",
        skillFocus: "Tactile Discrimination",
        messiness: "Low"
    },
    {
        id: 70,
        title: "Obstacle Course Problems",
        ageRange: "2-3",
        description: "Create simple problems to solve in an obstacle course, like moving a cushion to cross an area.",
        materials: ["Household items for obstacles"],
        setupTime: "10+ min",
        activityLength: "15+ min",
        category: "cognitive",
        skillFocus: "Problem Solving",
        messiness: "Low"
    },
    
    // Sensory Exploration Activities (17 activities)
    {
        id: 71,
        title: "Sensory Bin - Rice",
        ageRange: "2-3",
        description: "Explore a bin filled with rice and hidden objects to develop tactile sensitivity and fine motor skills.",
        materials: ["Large container", "Rice", "Small toys or objects", "Scoops"],
        setupTime: "10+ min",
        activityLength: "15+ min",
        category: "sensory",
        skillFocus: "Tactile Exploration",
        messiness: "Medium"
    },
    {
        id: 72,
        title: "Water Play",
        ageRange: "2-3",
        description: "Pour, fill, and splash with water to develop sensory awareness and understand basic properties of liquids.",
        materials: ["Water table or large container", "Cups", "Funnels", "Toys"],
        setupTime: "5 min",
        activityLength: "15+ min",
        category: "sensory",
        skillFocus: "Tactile Exploration",
        messiness: "High"
    },
    {
        id: 73,
        title: "Scented Playdough",
        ageRange: "2-3",
        description: "Explore playdough scented with extracts or spices to combine tactile and olfactory sensory input.",
        materials: ["Playdough", "Food extracts or spices"],
        setupTime: "5 min",
        activityLength: "15+ min",
        category: "sensory",
        skillFocus: "Multi-sensory",
        messiness: "Medium"
    },
    {
        id: 74,
        title: "Light Table Exploration",
        ageRange: "2-3",
        description: "Explore transparent and translucent objects on a light table or box to develop visual discrimination.",
        materials: ["Light table/box", "Transparent/translucent objects"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "sensory",
        skillFocus: "Visual Exploration",
        messiness: "Low"
    },
    {
        id: 75,
        title: "Texture Walk",
        ageRange: "2-3",
        description: "Walk on different textured surfaces (bubble wrap, fabric, etc.) to develop tactile awareness through feet.",
        materials: ["Various textured materials", "Tape"],
        setupTime: "10+ min",
        activityLength: "10 min",
        category: "sensory",
        skillFocus: "Tactile Exploration",
        messiness: "Low"
    },
    {
        id: 76,
        title: "Sound Bottles",
        ageRange: "2-3",
        description: "Shake bottles filled with different materials to create and compare sounds.",
        materials: ["Plastic bottles with lids", "Various filling materials"],
        setupTime: "10+ min",
        activityLength: "10 min",
        category: "sensory",
        skillFocus: "Auditory Exploration",
        messiness: "Low"
    },
    {
        id: 77,
        title: "Texture Collage",
        ageRange: "2-3",
        description: "Create a collage using materials with different textures to explore tactile differences.",
        materials: ["Cardboard or paper", "Glue", "Various textured materials"],
        setupTime: "5 min",
        activityLength: "15+ min",
        category: "sensory",
        skillFocus: "Tactile Exploration",
        messiness: "Medium"
    },
    {
        id: 78,
        title: "Scent Matching",
        ageRange: "2-3",
        description: "Match containers with the same scents to develop olfactory discrimination.",
        materials: ["Containers with lids", "Scented materials (spices, extracts)"],
        setupTime: "5 min",
        activityLength: "5 min",
        category: "sensory",
        skillFocus: "Olfactory Exploration",
        messiness: "Low"
    },
    {
        id: 79,
        title: "Sensory Bin - Beans",
        ageRange: "2-3",
        description: "Explore dried beans in a large container with scoops and containers to develop tactile sensitivity.",
        materials: ["Large container", "Dried beans", "Scoops", "Small containers"],
        setupTime: "5 min",
        activityLength: "15+ min",
        category: "sensory",
        skillFocus: "Tactile Exploration",
        messiness: "Medium"
    },
    {
        id: 80,
        title: "Ice Melting Play",
        ageRange: "2-3",
        description: "Explore ice as it melts, observing changes in temperature, texture, and state.",
        materials: ["Ice cubes", "Tray", "Warm water (optional)"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "sensory",
        skillFocus: "Temperature Awareness",
        messiness: "Medium"
    },
    {
        id: 81,
        title: "Color Mixing with Finger Paint",
        ageRange: "2-3",
        description: "Mix primary colors with fingers to discover how colors change and blend.",
        materials: ["Finger paint (red, yellow, blue)", "Paper", "Smock/old shirt"],
        setupTime: "5 min",
        activityLength: "15+ min",
        category: "sensory",
        skillFocus: "Visual Exploration",
        messiness: "High"
    },
    {
        id: 82,
        title: "Sensory Bottles",
        ageRange: "2-3",
        description: "Observe sealed bottles filled with water, oil, and food coloring to develop visual tracking and focus.",
        materials: ["Clear bottles", "Water", "Oil", "Food coloring", "Small objects (optional)"],
        setupTime: "10+ min",
        activityLength: "10 min",
        category: "sensory",
        skillFocus: "Visual Exploration",
        messiness: "Low"
    },
    {
        id: 83,
        title: "Squishy Bags",
        ageRange: "2-3",
        description: "Squish sealed bags filled with hair gel or paint to explore texture without mess.",
        materials: ["Ziplock bags", "Hair gel or paint", "Tape"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "sensory",
        skillFocus: "Tactile Exploration",
        messiness: "Low"
    },
    {
        id: 84,
        title: "Feely Box",
        ageRange: "2-3",
        description: "Feel objects hidden in a box and describe or identify them by touch alone.",
        materials: ["Box with hand hole", "Various objects"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "sensory",
        skillFocus: "Tactile Discrimination",
        messiness: "Low"
    },
    {
        id: 85,
        title: "Bubble Wrap Painting",
        ageRange: "2-3",
        description: "Paint on bubble wrap and press paper over it to create textured prints.",
        materials: ["Bubble wrap", "Non-toxic water-based paint", "Paper", "Smock/old shirt"],
        setupTime: "5 min",
        activityLength: "15+ min",
        category: "sensory",
        skillFocus: "Tactile and Visual",
        messiness: "Medium"
    },
    {
        id: 86,
        title: "Nature Sensory Tray",
        ageRange: "2-3",
        description: "Explore natural materials like pine cones, leaves, and stones on a tray to connect with nature textures.",
        materials: ["Tray", "Natural materials"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "sensory",
        skillFocus: "Natural Textures",
        messiness: "Low"
    },
    {
        id: 87,
        title: "Musical Instruments Exploration",
        ageRange: "2-3",
        description: "Explore different sounds made by simple instruments to develop auditory discrimination.",
        materials: ["Simple instruments or homemade noise makers"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "sensory",
        skillFocus: "Auditory Exploration",
        messiness: "Low"
    },
    
    // Social & Emotional Development Activities (13 activities)
    {
        id: 88,
        title: "Emotion Cards",
        ageRange: "2-3",
        description: "Look at pictures of faces showing different emotions and talk about feelings to develop emotional literacy.",
        materials: ["Emotion picture cards"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "social",
        skillFocus: "Emotional Literacy",
        messiness: "Low"
    },
    {
        id: 89,
        title: "Mirror Emotions",
        ageRange: "2-3",
        description: "Make different emotion faces in a mirror to connect facial expressions with feeling words.",
        materials: ["Mirror"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "social",
        skillFocus: "Emotional Awareness",
        messiness: "Low"
    },
    {
        id: 90,
        title: "Turn-Taking Games",
        ageRange: "2-3",
        description: "Play simple games that require taking turns to develop patience and social awareness.",
        materials: ["Simple board games", "Ball for rolling"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "social",
        skillFocus: "Turn-Taking",
        messiness: "Low"
    },
    {
        id: 91,
        title: "Cooperative Art",
        ageRange: "2-3",
        description: "Create art together on the same paper to practice sharing space and collaborating.",
        materials: ["Large paper", "Crayons or markers"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "social",
        skillFocus: "Cooperation",
        messiness: "Medium"
    },
    {
        id: 92,
        title: "Doll or Stuffed Animal Care",
        ageRange: "2-3",
        description: "Practice caring for dolls or stuffed animals to develop empathy and nurturing skills.",
        materials: ["Dolls or stuffed animals", "Pretend care items"],
        setupTime: "2 min",
        activityLength: "15+ min",
        category: "social",
        skillFocus: "Empathy",
        messiness: "Low"
    },
    {
        id: 93,
        title: "Sharing Snack",
        ageRange: "2-3",
        description: "Practice sharing a snack with others to develop generosity and awareness of others' needs.",
        materials: ["Snack items", "Plates"],
        setupTime: "5 min",
        activityLength: "10 min",
        category: "social",
        skillFocus: "Sharing",
        messiness: "Low"
    },
    {
        id: 94,
        title: "Feeling Songs",
        ageRange: "2-3",
        description: "Sing songs about feelings and use gestures to express emotions in a safe, fun way.",
        materials: ["List of emotion songs"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "social",
        skillFocus: "Emotional Expression",
        messiness: "Low"
    },
    {
        id: 95,
        title: "Helping Activities",
        ageRange: "2-3",
        description: "Engage in simple helping tasks like putting toys away or wiping a table to develop a sense of responsibility.",
        materials: ["Child-sized cleaning tools", "Tasks appropriate for toddlers"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "social",
        skillFocus: "Responsibility",
        messiness: "Low"
    },
    {
        id: 96,
        title: "Simple Role Play",
        ageRange: "2-3",
        description: "Act out familiar scenarios like grocery shopping or doctor visits to practice social roles and scripts.",
        materials: ["Props related to scenario"],
        setupTime: "5 min",
        activityLength: "15+ min",
        category: "social",
        skillFocus: "Social Understanding",
        messiness: "Low"
    },
    {
        id: 97,
        title: "Calming Corner",
        ageRange: "2-3",
        description: "Create a comfortable space with calming items to practice self-regulation during big emotions.",
        materials: ["Soft pillows", "Calming toys", "Books"],
        setupTime: "10+ min",
        activityLength: "As needed",
        category: "social",
        skillFocus: "Self-Regulation",
        messiness: "Low"
    },
    {
        id: 98,
        title: "Balloon Volleyball",
        ageRange: "2-3",
        description: "Keep a balloon in the air together to practice teamwork and coordination.",
        materials: ["Balloon"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "social",
        skillFocus: "Cooperation",
        messiness: "Low"
    },
    {
        id: 99,
        title: "Emotion Storytime",
        ageRange: "2-3",
        description: "Read stories about characters experiencing different emotions to develop emotional understanding.",
        materials: ["Books featuring emotional themes"],
        setupTime: "2 min",
        activityLength: "10 min",
        category: "social",
        skillFocus: "Emotional Literacy",
        messiness: "Low"
    },
    {
        id: 100,
        title: "Gratitude Circle",
        ageRange: "2-3",
        description: "Take turns sharing something you're thankful for to develop gratitude and positive emotional awareness.",
        materials: ["None needed", "Optional: special sharing object to hold"],
        setupTime: "2 min",
        activityLength: "5 min",
        category: "social",
        skillFocus: "Gratitude",
        messiness: "Low"
    },
// Food Preparation Activities (starting at ID 101)
{
    id: 101,
    title: "Simple Lemonade Making",
    ageRange: "2-3",
    description: "Help make homemade lemonade by squeezing lemons, measuring sugar, and stirring the ingredients. Develops fine motor skills and introduces simple math concepts.",
    materials: ["Lemons", "Sugar", "Water", "Measuring cups", "Pitcher", "Wooden spoon"],
    setupTime: "5 min",
    activityLength: "10 min",
    category: "cognitive",
    skillFocus: "Following Steps",
    messiness: "Medium"
},
{
    id: 102,
    title: "Homemade Granola Helper",
    ageRange: "2-3",
    description: "Mix oats, honey, and other ingredients to create simple granola. Toddlers practice measuring, pouring, and mixing while learning about healthy foods.",
    materials: ["Rolled oats", "Honey", "Cinnamon", "Mixing bowl", "Measuring cups", "Baking sheet"],
    setupTime: "5 min",
    activityLength: "15+ min",
    category: "sensory",
    skillFocus: "Measurement",
    messiness: "Medium"
},
{
    id: 103,
    title: "Fruit Parfait Assembly",
    ageRange: "2-3",
    description: "Create layered yogurt parfaits with fruit and granola. Develops fine motor control, pattern recognition, and introduces concepts of layering and sequencing.",
    materials: ["Yogurt", "Berries or cut fruit", "Granola", "Clear cups", "Small spoons"],
    setupTime: "5 min",
    activityLength: "10 min",
    category: "cognitive",
    skillFocus: "Sequencing",
    messiness: "Medium"
},
{
    id: 104,
    title: "Smoothie Making",
    ageRange: "2-3",
    description: "Help add pre-measured ingredients to a blender to make a fruit smoothie. Introduces cause and effect as ingredients transform into a drinkable treat.",
    materials: ["Frozen fruit", "Yogurt", "Milk or juice", "Blender", "Measuring cups"],
    setupTime: "5 min",
    activityLength: "10 min",
    category: "sensory",
    skillFocus: "Cause and Effect",
    messiness: "Medium"
},
{
    id: 105,
    title: "Veggie & Dip Cups",
    ageRange: "2-3",
    description: "Arrange pre-cut vegetables and prepare simple dip cups. Develops fine motor skills while encouraging healthy eating and food exploration.",
    materials: ["Pre-cut vegetables", "Dip (hummus, yogurt)", "Small cups", "Serving tray"],
    setupTime: "5 min",
    activityLength: "10 min",
    category: "motor",
    skillFocus: "Fine Motor",
    messiness: "Low"
},
{
    id: 106,
    title: "Banana Bread Helpers",
    ageRange: "2-3",
    description: "Mash bananas and help mix simple banana bread ingredients. Develops hand strength through mashing and mixing while following a sequence of steps.",
    materials: ["Ripe bananas", "Mixing bowl", "Wooden spoon", "Measuring cups", "Pre-measured dry ingredients"],
    setupTime: "10+ min",
    activityLength: "15+ min",
    category: "motor",
    skillFocus: "Hand Strength",
    messiness: "Medium"
},
{
    id: 107,
    title: "Trail Mix Creation",
    ageRange: "2-3",
    description: "Combine cereals, dried fruits, and other items to create a personalized trail mix. Develops sorting, counting, and fine motor skills.",
    materials: ["Cereals", "Dried fruit", "Small containers", "Mixing bowl", "Measuring cups"],
    setupTime: "5 min",
    activityLength: "10 min",
    category: "cognitive",
    skillFocus: "Counting",
    messiness: "Low"
},
{
    id: 108,
    title: "Fruit Popsicle Making",
    ageRange: "2-3",
    description: "Pour fruit juice or yogurt into popsicle molds to create frozen treats. Develops pouring skills and introduces concepts of liquid to solid transformation.",
    materials: ["Fruit juice or yogurt", "Popsicle molds", "Small pitcher", "Cut fruit (optional)"],
    setupTime: "5 min",
    activityLength: "10 min",
    category: "sensory",
    skillFocus: "Transformation",
    messiness: "Medium"
},
{
    id: 109,
    title: "No-Bake Energy Balls",
    ageRange: "2-3",
    description: "Mix nut butter, oats, and honey, then roll into small balls. Develops hand-eye coordination and fine motor skills through rolling and shaping.",
    materials: ["Oats", "Nut butter", "Honey", "Mix-ins (chocolate chips, dried fruit)", "Mixing bowl"],
    setupTime: "5 min",
    activityLength: "15+ min",
    category: "motor",
    skillFocus: "Fine Motor",
    messiness: "Medium"
},
{
    id: 110,
    title: "English Muffin Pizzas",
    ageRange: "2-3",
    description: "Spread sauce and sprinkle toppings on English muffin halves to create mini pizzas. Develops spreading skills and creativity in food preparation.",
    materials: ["English muffins", "Pizza sauce", "Shredded cheese", "Toppings", "Baking sheet"],
    setupTime: "5 min",
    activityLength: "15+ min",
    category: "motor",
    skillFocus: "Spreading Skills",
    messiness: "Medium"
},
{
    id: 111,
    title: "Fruit-Infused Water",
    ageRange: "2-3",
    description: "Add fruit slices and herbs to water to create flavored drinks. Develops sensory awareness of subtle flavors while encouraging hydration.",
    materials: ["Water pitcher", "Sliced fruits", "Fresh herbs (mint, basil)", "Cups", "Wooden spoon"],
    setupTime: "5 min",
    activityLength: "5 min",
    category: "sensory",
    skillFocus: "Taste Exploration",
    messiness: "Low"
},
{
    id: 112,
    title: "Yogurt Bark Decorating",
    ageRange: "2-3",
    description: "Spread yogurt on a tray and sprinkle with fruits and toppings to create frozen yogurt bark. Develops fine motor control and pattern creation.",
    materials: ["Yogurt", "Small fruits", "Honey", "Baking sheet with parchment paper"],
    setupTime: "5 min",
    activityLength: "10 min",
    category: "motor",
    skillFocus: "Fine Motor",
    messiness: "Medium"
},
{
    id: 113,
    title: "Tortilla Roll-Ups",
    ageRange: "2-3",
    description: "Spread soft fillings on tortillas and roll them up to make simple snacks. Develops spreading and rolling skills while creating a healthy snack.",
    materials: ["Small tortillas", "Spreadable fillings (cream cheese, hummus)", "Sliced veggies", "Plastic knife"],
    setupTime: "5 min",
    activityLength: "10 min",
    category: "motor",
    skillFocus: "Rolling Skills",
    messiness: "Low"
},
{
    id: 114,
    title: "Overnight Oats Preparation",
    ageRange: "2-3",
    description: "Help measure and add ingredients to jars to create overnight oats. Introduces concepts of transformation as ingredients change texture overnight.",
    materials: ["Oats", "Milk", "Yogurt", "Fruits", "Honey", "Jars with lids", "Measuring cups"],
    setupTime: "5 min",
    activityLength: "10 min",
    category: "cognitive",
    skillFocus: "Measurement",
    messiness: "Low"
},
{
    id: 115,
    title: "Vegetable Stamp Prints",
    ageRange: "2-3",
    description: "Cut vegetables in half and use them as natural stamps for art projects. Creates beautiful patterns while exploring plant structures and textures.",
    materials: ["Vegetables (bell peppers, celery, okra)", "Paint (optional)", "Paper", "Shallow trays"],
    setupTime: "5 min",
    activityLength: "15+ min",
    category: "sensory",
    skillFocus: "Creative Expression",
    messiness: "Medium"
}
];
